name: SiteSerenity Autofix

on:
  workflow_dispatch: {}

permissions:
  contents: write
  pull-requests: write

jobs:
  autofix:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Ensure next-auth type augmentation
        run: |
          set -euo pipefail
          mkdir -p src/types
          cat > src/types/next-auth.d.ts <<'EOF'
          import { DefaultSession } from "next-auth";

          declare module "next-auth" {
            interface Session {
              accessToken?: string;
              discordId?: string;
              user: {
                id?: string;
              } & DefaultSession["user"];
            }
          }

          declare module "next-auth/jwt" {
            interface JWT {
              accessToken?: string;
              discordId?: string;
            }
          }

          export {};
EOF

      - name: Ensure tsconfig include
        run: |
          set -euo pipefail
          if [ -f tsconfig.json ]; then
            node - <<'NODE'
            const fs = require('fs');
            const path = 'tsconfig.json';
            const json = JSON.parse(fs.readFileSync(path, 'utf8'));
            json.include = json.include || [];
            if (!json.include.includes('src/types/**/*.d.ts')) {
              json.include.push('src/types/**/*.d.ts');
            }
            fs.writeFileSync(path, JSON.stringify(json, null, 2) + '\n');
NODE
          else
            echo "tsconfig.json not found, skipping"
          fi

      - name: Normalize src/auth.ts (optional hard replace)
        run: |
          set -euo pipefail
          if grep -q "@ts-expect-error" src/auth.ts || ! grep -q "async session({ s
